---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memphis.svcName" . }}
  namespace: {{ include "nats.namespace" . }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
  {{- if .Values.serviceAnnotations}}
  annotations:
  {{- range $key, $value := .Values.serviceAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}
  clusterIP: None
  {{- if .Values.topologyKeys }}
  topologyKeys:
     {{- .Values.topologyKeys | toYaml | nindent 4 }}
  {{- end }}
  ports:
  - name: memphis-cp-management
    port: 9000
    targetPort: 9000
  - name: memphis-ws
    port: 7770
    targetPort: 7770
  - name: memphis-cp-tcp
    port: 6666
    targetPort: 6666
  - name: monitor
    port: 8222
  - name: debug
    port: 4000
    
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memphis.svcName" . }}-external
  namespace: {{ include "nats.namespace" . }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  selector:
    {{- include "nats.selectorLabels" . | nindent 4 }}
  {{- if .Values.topologyKeys }}
  topologyKeys:
     {{- .Values.topologyKeys | toYaml | nindent 4 }}
  {{- end }}
  ports:
  - name: memphis-cp-management
    port: 9000
    targetPort: 9000
  - name: https
    port: 443
    targetPort: 9000
  - name: memphis-ws
    port: 7770
    targetPort: 7770
  - name: memphis-cp-tcp
    port: 6666
    targetPort: 6666
