apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-jwt
  namespace: {{ include "nats.namespace" . }}
data:
  KO.jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJCVkNLTE40UDVSTFdHMjdRV0VKVlpIVjJKU0c1QTZCRU1SU05OMjM2WVZURENJVDVLWUxRIiwiaWF0IjoxNjQ4NTg0MjE1LCJpc3MiOiJPQUxUV0w3M0pLR1AzUklTQ0lRQ0VFSkdJMk5GTEhFUkdRM0dOT1pEMklPTEpRUURETUUzSzJZTyIsIm5hbWUiOiJvcDMiLCJzdWIiOiJPQUxUV0w3M0pLR1AzUklTQ0lRQ0VFSkdJMk5GTEhFUkdRM0dOT1pEMklPTEpRUURETUUzSzJZTyIsIm5hdHMiOnsidHlwZSI6Im9wZXJhdG9yIiwidmVyc2lvbiI6Mn19.-LKA_1D7SUETEYBVPGwBLccQ0GvjK2em9io6VWx9FBaQZW3uIpOom99sNA7Kp4P4i9kdxBTPrF2J69AZvgY6Bg
